<a href="https://colab.research.google.com/github/zrghassabi/DeepLearning/blob/main/Using_Autograd%5B1%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

In [1]:
import torch

In [3]:
w=torch.randn(4,3,requires_grad=True)
w

tensor([[ 0.4696,  0.0385,  0.5215],
        [ 0.5331, -1.2261,  0.8514],
        [ 0.7582,  1.0256, -1.1996],
        [ 1.3019, -2.4264,  0.4628]], requires_grad=True)

In [5]:
w.requires_grad_(False)

tensor([[ 0.4696,  0.0385,  0.5215],
        [ 0.5331, -1.2261,  0.8514],
        [ 0.7582,  1.0256, -1.1996],
        [ 1.3019, -2.4264,  0.4628]])

In [6]:
w.requires_grad_(True)

tensor([[ 0.4696,  0.0385,  0.5215],
        [ 0.5331, -1.2261,  0.8514],
        [ 0.7582,  1.0256, -1.1996],
        [ 1.3019, -2.4264,  0.4628]], requires_grad=True)

In [8]:
y=torch.exp(w)
y

tensor([[1.5994, 1.0393, 1.6846],
        [1.7042, 0.2934, 2.3429],
        [2.1343, 2.7889, 0.3013],
        [3.6763, 0.0884, 1.5886]], grad_fn=<ExpBackward0>)

In [9]:
print(y.grad_fn)

In [10]:
output=y.mean()
print(output)

tensor(1.6035, grad_fn=<MeanBackward0>)


In [11]:
print(w.grad)

None


In [12]:
output.backward()

In [13]:
w.grad

tensor([[0.1333, 0.0866, 0.1404],
        [0.1420, 0.0245, 0.1952],
        [0.1779, 0.2324, 0.0251],
        [0.3064, 0.0074, 0.1324]])

In [14]:
print(output.requires_grad)

True


In [15]:
with torch.no_grad():
  output=(w+y).mean()

print(output.grad)

None


In [16]:
output

tensor(1.6960)